# compiler flags.  -g for debug, -O3 for optimization
CFLAGS=-g -O3

# first target is built by default
all: asciidraw

# include file dependencies
draw.o: draw.h
print_rectangle.o: draw.h
print_triangle.o: draw.h
main.o: draw.h

# $@=target, $^=prerequisites
asciidraw: draw.o print_triangle.o print_rectangle.o main.o
	cc -o $@ $^ $(CFLAGS)

# deletes files generated by compilation
clean:
	rm -f *.o sortargs