# compiler flags.  -g for debug, -O3 for optimization
CFLAGS=-g -O3

OBJS=triangle.o rectangle.o font-11x16.o char_11x16.o uimain.o


# first target is built by default
all: asciidraw

# include file dependencies
$(OBJS): draw.h


# $@=target, $^=prerequisites
asciidraw: $(OBJS)
	cc -o $@ $^ $(CFLAGS)

# deletes files generated by compilation
clean:
	rm -f *.o asciidraw

run:asciidraw
	./asciidraw
