# compiler flags.  -g for debug, -O3 for optimization
CFLAGS=-g -O3

OBJS= draw_shapes.o draw_chars.o 11x16font.o uimain.o


# first target is built by default
all: asciidraw

# include file dependencies
$(OBJS): draw.h


# $@=target, $^=prerequisites
asciidraw: $(OBJS)
	cc -o $@ $^ $(CFLAGS)

# deletes files generated by compilation
clean:
	rm -f *.o asciidraw

run:asciidraw
	./asciidraw
